workflows:
  android-release-workflow:
    name: Android Release Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Build Flutter App Bundle
        script: |
          cd mobile_app
          flutter pub get
          flutter build appbundle --release
    artifacts:
      - mobile_app/build/app/outputs/bundle/release/*.aab
