workflows:
  android-release:
    name: X Cash Android Release
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Build App Bundle with Command Line Signing
        script: |
          cd mobile_app
          flutter build appbundle --release \
            --android-signing-key-path=android/app/key.jks \
            --android-signing-key-password=123456 \
            --android-signing-key-alias=key \
            --android-signing-store-password=123456
    artifacts:
      - mobile_app/build/app/outputs/bundle/release/*.aab
