workflows:
  android-release:
    name: X Cash Android Release
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Build Unsigned App Bundle
        script: |
          cd mobile_app
          flutter build appbundle --release --no-pub
    artifacts:
      - mobile_app/build/app/outputs/bundle/release/*.aab
