workflows:
  android-release:
    name: X Cash Android Release
    max_build_duration: 30
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Generate Keystore
        script: |
          cd mobile_app/android/app
          keytool -genkey -v -keystore key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias key -storepass 123456 -keypass 123456 -dname "CN=Walid, OU=XCash, O=XCash, L=Dubai, ST=Dubai, C=AE"
          echo "Checking generated keystore file:"
          ls -la key.jks
      - name: Build App Bundle
        script: |
          cd mobile_app
          flutter build appbundle --release --android-skip-build-dependency-validation
    artifacts:
      - mobile_app/build/app/outputs/bundle/release/*.aab
