allprojects {
    // إجبار كل مشروع فرعي على تفعيل AndroidX وJetifier
    project.ext.set("android.useAndroidX", true)
    project.ext.set("android.enableJetifier", true)

    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
