name: Build Flutter App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      - name: Install dependencies & Generate Icons
        run: |
          cd mobile_app
          flutter pub get
          flutter pub run flutter_launcher_icons:main

      - name: Build Android App Bundle (AAB)
        run: |
          cd mobile_app
          flutter build appbundle --release
